name: wbutton_uzversion
description: "This package created for better and faster write code"
version: 0.0.2
author: Muhammadrasul <muhammadrasulcyber@gmail.com>
homepage: https://github.com/hamidovdev/wbutton_uzversion
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0